

const ALERT='ALERT';
const REFECH_CHATS='REFECH_CHATS';

const NEW_ATTACHMENT = "NEW_ATTACHMENT";
const NEW_MESSAGE_ALERT = "NEW_MESSAGE_ALERT"; 

const NEW_MESSAGE="NEW_MESSAGE";

const NEW_REQUEST="NEW_REQUEST";

const START_TYPING = "START_TYPING";
const STOP_TYPING = "STOP_TYPING";

export { 
    ALERT,
    REFECH_CHATS,
    NEW_ATTACHMENT,
    NEW_MESSAGE_ALERT,
    NEW_REQUEST,
    NEW_MESSAGE,
    START_TYPING,
    STOP_TYPING,
};