

const ALERT='ALERT';
const REFECH_CHATS='REFECH_CHATS';

const NEW_ATTACHMENT = "NEW_ATTACHMENT";
const NEW_MESSAGE_ALERT = "NEW_MESSAGE_ALERT"; 

const NEW_REQUEST="NEW_REQUEST";

export { ALERT,REFECH_CHATS,NEW_ATTACHMENT,NEW_MESSAGE_ALERT,NEW_REQUEST };